"""Flight planning tolerances and engineering limits."""

ORBIT_MAINTENANCE_EXIT_HYSTERESIS = 0.8
CONTROLLED_DEORBIT_PERIAPSIS_ALTITUDE_M = 80_000.0
FINITE_BURN_RESIDUAL_TOLERANCE_M_S = 0.01
FINITE_BURN_TIME_TOLERANCE_SECONDS = 1.0e-6
FINITE_BURN_MAX_ITERATIONS = 50
PLANNING_PROPAGATION_STEP_SECONDS = 1.0
PLANNING_ZERO_DELTA_V_M_S = 1.0e-6
AVOIDANCE_MANEUVER_LEAD_FRACTION = 0.5

# Dimensionless controller fractions scale each satellite's catalog torque.
ATTITUDE_PROPORTIONAL_GAIN = 0.8
ATTITUDE_INTEGRAL_GAIN = 0.05
ATTITUDE_DERIVATIVE_GAIN = 0.3
ATTITUDE_INTEGRAL_LIMIT_RAD_S = 0.5
BURN_ALIGNMENT_TOLERANCE_RAD = 0.02
WHEEL_UNLOAD_START_FRACTION = 0.8
